export const apiGetListSubject = "subject/getListSubject"
export const apiCreateSubject = "subject/createSubject"
export const apiDeleteSubject = "subject/deleteSubject"
export const apiUpdateSubject = "subject/updateSubject"
export const apiGetDetailSubject = "subject/getDetailSubject"
export const apiGetListTopSubject = "subject/getListTopSubject"
export const apiGetListSubjectByAdmin = "subject/getListSubjectByAdmin"