export const apiGetListSubject = "subject/getListSubject"
export const apiCreateSubject = "subject/createSubject"
export const apiDeleteSubject = "subject/deleteSubject"
export const apiUpdateSubject = "subject/updateSubject"
export const apiGetListRecommendSubject = "subject/getListRecommendSubject"