export const apiCreateTimeTable = "timetable/createTimeTable"
export const apiGetTimeTableOfTeacherOrStudent = "timetable/getTimeTableOfTeacherOrStudent"
export const apiAttendanceTimeTable = "timetable/attendanceTimeTable"
export const apiUpdateTimeTable = "timetable/updateTimeTable"
export const apiGetTimeTableByUser = "timetable/getTimeTableByUser"
export const apiAttendanceOrCancelTimeTable = "timetable/attendanceOrCancelTimeTable"