export const apiGetListSubjectCate = "subjectcate/getListSubjectCate"
export const apiCreateSubjectCate = "subjectcate/createSubjectCate"
export const apiDeleteSubjectCate = "subjectcate/deleteSubjectCate"
export const apiUpdateSubjectCate = "subjectcate/updateSubjectCate"
export const apiGetListSubjectCateAndSubject = "subjectcate/getListSubjectCateAndSubject"
export const apiGetDetailSubjectCate = "subjectcate/getDetailSubjectCate"