export const apiStatisticTotalUser = "statistic/statisticTotalUser"
export const apiStatisticNewRegisteredUser = "statistic/statisticNewRegisteredUser"
export const apiStatisticTotalBooking = "statistic/statisticTotalBooking"
export const apiStatisticFinancial = "statistic/statisticFinancial"
export const apiStatisticTopTeacher = "statistic/statisticTopTeacher"
export const apiStatisticBooking = "statistic/statisticBooking"