export const apiGetListSystemKey = "common/getListSystemkey"
export const apiGetProfitPercent = "common/getProfitPercent"
export const apiChangeProfitPercent = "common/changeProfitPercent"
export const apiTeacherRecommend = "common/teacherRecommend"
export const apiGetListTabs = "common/getListTabs"
export const apiTeacherRecommendationByLearnHistory = "common/teacherRecommendationByLearnHistory"
export const apiGetTotalUserAndSubject = "common/getTotalUserAndSubject"
export const apiChatBot = "common/chatbot"