export const apiCreateBlog = "blog/createBlog"
export const apiUpdateBlog = "blog/updateBlog"
export const apiGetListBlog = "blog/getListBlog"
export const apiDeleteBlog = "blog/deleteBlog"
export const apiFollowBlog = "blog/followBlog"
export const apiGetDetailBlog = "blog/getDetailBlog"
export const apiGetListBlogOfUser = "blog/getListBlogByUser"